set(VCPKG_TARGET_ARCHITECTURE arm64)
set(VCPKG_CRT_LINKAGE static)
set(VCPKG_LIBRARY_LINKAGE static)

set(VCPKG_ENV_PASSTHROUGH_UNTRACKED "VCPKG_ROOT;LLVM_DIR")

if (PORT MATCHES "harfbuzz|libwebp")
    unset(ENV{LLVM_DIR})
endif ()

set(VCPKG_CHAINLOAD_TOOLCHAIN_FILE ${CMAKE_CURRENT_LIST_DIR}/../toolchains/windows.cmake)

set(VCPKG_LOAD_VCVARS_ENV ON)
