site_name: Brisk
site_url: https://docs.brisklib.com

theme:
  name: "material"
  custom_dir: custom/
  font:
    text: Source Sans 3
  features:
    - content.tabs.link
    - navigation.footer
    - navigation.instant
    - navigation.instant.progress
    - navigation.tabs
    - navigation.top
    - content.code.copy
    - toc.integrate
    - toc.follow
  palette:
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
      media: "(prefers-color-scheme: light)"
      primary: deep purple
      accent: light green

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
      media: "(prefers-color-scheme: dark)"
      primary: deep purple
      accent: light green

extra:
  search:
    language: en

  social:
    - icon: fontawesome/brands/github-alt
      link: "https://github.com/brisklib"
    - icon: fontawesome/brands/twitter
      link: "https://twitter.com/brisklib"

copyright: "Copyright &copy; 2025 Brisk"

extra_css:
  - style.css

plugins:
  - search
  - privacy
  - glightbox

markdown_extensions:
  - attr_list
  - admonition
  - footnotes
  - meta
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.details
  - pymdownx.magiclink
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

repo_url: https://github.com/brisklib/brisk
repo_name: Brisk
edit_uri: edit/main/docs/

nav:
  - Brisk:
    - index.md
    - about.md
    - Getting Started:
      - getting_started/prerequisites.md
      - getting_started/prebuilt_binaries.md
      - getting_started/building.md
      - getting_started/hello_world.md
    - Basic usage:
      - basic/binding.md
      - basic/resources.md
      - basic/graphics.md
    - Widgets:
      - widgets/all.md
      - widgets/button.md
      - widgets/combobox.md
      - widgets/checkbox.md
      - widgets/colorbutton.md
      - widgets/colorpalette.md
      - widgets/colorsliders.md
      - widgets/colorview.md
      - widgets/dot.md
      - widgets/gradientview.md
      - widgets/guide.md
      - widgets/hint.md
      - widgets/hyperlink.md
      - widgets/imageview.md
      - widgets/item.md
      - widgets/knob.md
      - widgets/line.md
      - widgets/listbox.md
      - widgets/menu.md
      - widgets/notificationview.md
      - widgets/page.md
      - widgets/pages.md
      - widgets/passwordeditor.md
      - widgets/popupbox.md
      - widgets/popupbutton.md
      - widgets/popupdialog.md
      - widgets/progress.md
      - widgets/radiobutton.md
      - widgets/scrollbox.md
      - widgets/shortcuthint.md
      - widgets/slider.md
      - widgets/spacer.md
      - widgets/spinbox.md
      - widgets/spinner.md
      - widgets/svgimageview.md
      - widgets/switch.md
      - widgets/tabbutton.md
      - widgets/table.md
      - widgets/tablecell.md
      - widgets/tableheader.md
      - widgets/tablerow.md
      - widgets/tabs.md
      - widgets/text.md
      - widgets/texteditor.md
      - widgets/togglebutton.md
      - widgets/updownbuttons.md
      - widgets/valuewidget.md
      - widgets/viewport.md
      - widgets/webgpuwidget.md
    - Advanced:
      - advanced/triplets.md
      - advanced/integrating.md
    - Examples:
      - other_examples.md
  - Reference:
      - index.md
  - Index:
      - auto/refindex.md

  - brisklib.com: https://brisklib.com
